import { ClinicalTemplate } from '@/src/types';

export const CLINICAL_TEMPLATES: ClinicalTemplate[] = [
  {
    id: 'pph',
    title: 'Obstetric Emergency: Severe PPH',
    subtitle: 'Postpartum Haemorrhage with Hypovolemic Shock',
    priority: 'CRITICAL',
    chiefComplaint: 'Severe Postpartum Haemorrhage',
    clinicalSummary:
      '28y G1P1 delivered at 02:00. Uterine atony unresponsive to oxytocin, misoprostol, & bimanual compression. Estimated blood loss 1,200 mL. Profound hypovolemic shock requiring emergency laparotomy and blood transfusion.',
    patient: {
      id: 'pat_pph_amara_okoro',
      name: 'Amara Okoro',
      age: 28,
      gender: 'FEMALE',
      bloodGroup: 'O_NEGATIVE',
      allergies: ['PENICILLIN'],
    },
    vitals: {
      bp_systolic: 74,
      bp_diastolic: 42,
      heart_rate: 138,
      respiratory_rate: 28,
      spo2: 91,
      temperature_celsius: 36.1,
      gcs_score: 14,
    },
    requiredResources: {
      bed_tier: 'RESUSCITATION',
      specialties: ['OBSTETRICIAN_GYNAECOLOGIST'],
      facilities: ['OPERATING_THEATRE'],
      blood_units: [{ blood_group: 'O_NEGATIVE', component: 'PRBC', quantity: 2 }],
      high_flow_oxygen: true,
      transport_type: 'ALS',
    },
  },
  {
    id: 'polytrauma',
    title: 'Trauma: Polytrauma & Hemorrhagic Shock',
    subtitle: 'High-Velocity Road Traffic Collision',
    priority: 'CRITICAL',
    chiefComplaint: 'Severe Polytrauma with Pelvic Instability',
    clinicalSummary:
      '34y M unrestrained driver in high-speed collision. Blunt abdominal trauma with positive FAST exam in splenorenal fossa, unstable open pelvic fracture, severe blood loss.',
    patient: {
      id: 'pat_trauma_babatunde',
      name: 'Babatunde Adeleke',
      age: 34,
      gender: 'MALE',
      bloodGroup: 'O_POSITIVE',
      allergies: ['NONE'],
    },
    vitals: {
      bp_systolic: 82,
      bp_diastolic: 48,
      heart_rate: 126,
      respiratory_rate: 30,
      spo2: 93,
      temperature_celsius: 35.8,
      gcs_score: 9,
    },
    requiredResources: {
      bed_tier: 'RESUSCITATION',
      specialties: ['TRAUMA_SURGEON', 'ORTHOPAEDIC_SURGEON'],
      facilities: ['OPERATING_THEATRE'],
      blood_units: [{ blood_group: 'O_NEGATIVE', component: 'PRBC', quantity: 4 }],
      high_flow_oxygen: true,
      transport_type: 'ALS',
    },
  },
  {
    id: 'neonatal_sepsis',
    title: 'Pediatrics: Neonatal Sepsis',
    subtitle: 'Early-Onset Sepsis with Respiratory Collapse',
    priority: 'CRITICAL',
    chiefComplaint: 'Severe Neonatal Sepsis & Decompensation',
    clinicalSummary:
      'Day 3 infant born at 36 weeks. Temperature 35.4°C (hypothermic), severe grunting, intercostal retractions, poor perfusion with capillary refill > 4 seconds.',
    patient: {
      id: 'pat_neo_fatima',
      name: 'Baby Fatima Hassan',
      age: 0,
      gender: 'FEMALE',
      bloodGroup: 'O_POSITIVE',
      allergies: ['NONE'],
    },
    vitals: {
      bp_systolic: 58,
      bp_diastolic: 32,
      heart_rate: 184,
      respiratory_rate: 68,
      spo2: 88,
      temperature_celsius: 35.4,
      gcs_score: 8,
    },
    requiredResources: {
      bed_tier: 'RESUSCITATION',
      specialties: ['PAEDIATRICIAN_NEONATOLOGIST'],
      facilities: ['NICU_INCUBATOR'],
      high_flow_oxygen: true,
      transport_type: 'ALS',
    },
  },
  {
    id: 'stemi_shock',
    title: 'Cardiovascular: Anterior STEMI',
    subtitle: 'Impending Cardiogenic Shock',
    priority: 'CRITICAL',
    chiefComplaint: 'Extensive Anterior STEMI',
    clinicalSummary:
      '58y M presenting with 4 hours of crushing substernal chest pain radiating to left arm. ECG shows marked 4mm ST elevation across leads V1-V4, clammy, diaphoretic.',
    patient: {
      id: 'pat_stemi_emeka',
      name: 'Emeka Obi',
      age: 58,
      gender: 'MALE',
      bloodGroup: 'A_POSITIVE',
      allergies: ['SULFA'],
    },
    vitals: {
      bp_systolic: 86,
      bp_diastolic: 54,
      heart_rate: 114,
      respiratory_rate: 24,
      spo2: 92,
      temperature_celsius: 36.6,
      gcs_score: 15,
    },
    requiredResources: {
      bed_tier: 'RESUSCITATION',
      specialties: ['INTERVENTIONAL_CARDIOLOGIST'],
      facilities: ['CATHETERIZATION_LABORATORY'],
      high_flow_oxygen: true,
      transport_type: 'ALS',
    },
  },
];
